// Glossary Terms Data

const glossaryTerms = [
    { term: 'Access Token', category: 'OAuth', definition: 'A credential used to access protected resources. Usually short-lived (15min-1hr) and sent with each API request.', related: ['Refresh Token', 'Bearer Token'] },
    { term: 'API Key', category: 'API', definition: 'A unique identifier used to authenticate API requests. Simple but less secure than OAuth. Should never be exposed in client-side code.', related: ['Authentication', 'Rate Limiting'] },
    { term: 'Authentication', category: 'Core', definition: 'The process of verifying the identity of a user or system. Answers the question "Who are you?"', related: ['Authorization', 'Identity'] },
    { term: 'Authorization', category: 'Core', definition: 'The process of determining what resources a user can access. Answers "What are you allowed to do?"', related: ['Authentication', 'Permissions'] },
    { term: 'Authorization Code', category: 'OAuth', definition: 'A short-lived code exchanged for tokens in the OAuth Authorization Code flow. Should be used once and immediately.', related: ['PKCE', 'OAuth 2.0'] },
    { term: 'Base64URL', category: 'Encoding', definition: 'A URL-safe variant of Base64 encoding that replaces + with - and / with _. Used in JWTs.', related: ['JWT', 'Encoding'] },
    { term: 'Bearer Token', category: 'OAuth', definition: 'A type of access token sent in the Authorization header. Format: "Authorization: Bearer {token}"', related: ['Access Token', 'Authorization Header'] },
    { term: 'Claim', category: 'JWT', definition: 'A piece of information in a JWT payload. Examples: sub (subject), iss (issuer), exp (expiration).', related: ['JWT', 'Payload'] },
    { term: 'Client Credentials', category: 'OAuth', definition: 'An OAuth grant type for machine-to-machine authentication. No user involvement, uses client ID and secret.', related: ['OAuth 2.0', 'M2M'] },
    { term: 'Client ID', category: 'OAuth', definition: 'A public identifier for an OAuth application. Can be exposed in client-side code.', related: ['Client Secret', 'OAuth 2.0'] },
    { term: 'Client Secret', category: 'OAuth', definition: 'A confidential credential for an OAuth application. Must NEVER be exposed in client-side code.', related: ['Client ID', 'PKCE'] },
    { term: 'Code Challenge', category: 'PKCE', definition: 'A SHA-256 hash of the code verifier, sent in the authorization request. Part of PKCE flow.', related: ['Code Verifier', 'PKCE'] },
    { term: 'Code Verifier', category: 'PKCE', definition: 'A random string (43-128 chars) used in PKCE. Kept secret and sent in the token request.', related: ['Code Challenge', 'PKCE'] },
    { term: 'CORS', category: 'Security', definition: 'Cross-Origin Resource Sharing. A mechanism that allows restricted resources to be requested from another domain.', related: ['Same-Origin Policy', 'Preflight'] },
    { term: 'CSRF', category: 'Security', definition: 'Cross-Site Request Forgery. An attack that tricks users into performing unwanted actions while authenticated. Prevented by CSRF tokens.', related: ['State Parameter', 'Session'] },
    { term: 'Expiration (exp)', category: 'JWT', definition: 'A JWT claim specifying when the token expires. Value is a Unix timestamp.', related: ['JWT', 'Claims', 'iat'] },
    { term: 'Grant Type', category: 'OAuth', definition: 'The method used to obtain an access token in OAuth. Examples: authorization_code, client_credentials, refresh_token.', related: ['OAuth 2.0', 'Flow'] },
    { term: 'Header', category: 'JWT', definition: 'The first part of a JWT containing metadata like algorithm (alg) and token type (typ).', related: ['JWT', 'Payload', 'Signature'] },
    { term: 'HMAC', category: 'Cryptography', definition: 'Hash-based Message Authentication Code. Used in HS256/384/512 JWT algorithms with symmetric keys.', related: ['HS256', 'Symmetric Key'] },
    { term: 'HS256', category: 'JWT Algorithm', definition: 'HMAC with SHA-256. A symmetric signing algorithm - same secret for signing and verification.', related: ['RS256', 'JWT', 'HMAC'] },
    { term: 'HttpOnly Cookie', category: 'Security', definition: 'A cookie flag that prevents JavaScript access. Protects against XSS attacks stealing session tokens.', related: ['XSS', 'Cookie', 'Session'] },
    { term: 'Identity Provider (IdP)', category: 'SSO', definition: 'A service that authenticates users and provides identity information. Examples: Auth0, Okta, Google.', related: ['OIDC', 'SAML', 'SSO'] },
    { term: 'Implicit Flow', category: 'OAuth', definition: 'DEPRECATED OAuth flow that returns tokens directly in URL. Replaced by Authorization Code + PKCE.', related: ['PKCE', 'OAuth 2.0'] },
    { term: 'Issuer (iss)', category: 'JWT', definition: 'A JWT claim identifying who created the token. Should be validated on the server.', related: ['JWT', 'Claims'] },
    { term: 'JWK', category: 'JWT', definition: 'JSON Web Key. A JSON format for representing cryptographic keys, often used for RSA public keys.', related: ['JWKS', 'RS256'] },
    { term: 'JWKS', category: 'JWT', definition: 'JSON Web Key Set. A collection of JWKs, typically served at /.well-known/jwks.json for key rotation.', related: ['JWK', 'Key Rotation'] },
    { term: 'JWT', category: 'Core', definition: 'JSON Web Token. A compact, URL-safe format for claims. Structure: header.payload.signature', related: ['Claims', 'Signature', 'Header'] },
    { term: 'Nonce', category: 'Security', definition: 'A random value used once to prevent replay attacks. Required in OIDC implicit flows.', related: ['Replay Attack', 'OIDC'] },
    { term: 'OAuth 2.0', category: 'Core', definition: 'An authorization framework that enables third-party access to resources without sharing passwords.', related: ['OIDC', 'Grant Type', 'Access Token'] },
    { term: 'OIDC', category: 'Core', definition: 'OpenID Connect. An identity layer on top of OAuth 2.0 that provides authentication and user info.', related: ['OAuth 2.0', 'ID Token', 'SSO'] },
    { term: 'Payload', category: 'JWT', definition: 'The second part of a JWT containing claims (data). Base64URL encoded but NOT encrypted.', related: ['JWT', 'Claims', 'Header'] },
    { term: 'PKCE', category: 'OAuth', definition: 'Proof Key for Code Exchange. Protects against authorization code interception. Mandatory for public clients.', related: ['Code Verifier', 'Code Challenge'] },
    { term: 'Redirect URI', category: 'OAuth', definition: 'The URL where the authorization server sends users after authentication. Must be pre-registered.', related: ['OAuth 2.0', 'Callback'] },
    { term: 'Refresh Token', category: 'OAuth', definition: 'A long-lived token used to obtain new access tokens without re-authentication. Should be stored securely.', related: ['Access Token', 'Token Rotation'] },
    { term: 'RS256', category: 'JWT Algorithm', definition: 'RSA with SHA-256. An asymmetric algorithm - private key signs, public key verifies.', related: ['HS256', 'JWT', 'RSA'] },
    { term: 'SAML', category: 'SSO', definition: 'Security Assertion Markup Language. An XML-based SSO standard, popular in enterprise environments.', related: ['SSO', 'OIDC', 'Enterprise'] },
    { term: 'Scope', category: 'OAuth', definition: 'Permissions requested by an application. Examples: read:user, write:posts, openid.', related: ['OAuth 2.0', 'Permissions'] },
    { term: 'Session', category: 'Core', definition: 'Server-side storage of user authentication state. Typically tracked via a session ID cookie.', related: ['Cookie', 'Stateful'] },
    { term: 'Signature', category: 'JWT', definition: 'The third part of a JWT that verifies the token hasnt been tampered with. Created by signing header.payload.', related: ['JWT', 'HMAC', 'Verification'] },
    { term: 'SSO', category: 'Core', definition: 'Single Sign-On. Allows users to authenticate once and access multiple applications.', related: ['SAML', 'OIDC', 'IdP'] },
    { term: 'State Parameter', category: 'OAuth', definition: 'A random value sent in OAuth requests to prevent CSRF. Should be verified when receiving the callback.', related: ['CSRF', 'OAuth 2.0'] },
    { term: 'Subject (sub)', category: 'JWT', definition: 'A JWT claim identifying the principal (user) the token represents. Usually a user ID.', related: ['JWT', 'Claims'] },
    { term: 'Token Rotation', category: 'Security', definition: 'Issuing new refresh tokens with each use, invalidating old ones. Limits damage from stolen tokens.', related: ['Refresh Token', 'Security'] },
    { term: 'XSS', category: 'Security', definition: 'Cross-Site Scripting. An attack that injects malicious scripts into web pages. Prevented by HttpOnly cookies.', related: ['HttpOnly', 'Security', 'Sanitization'] },
    { term: 'Zero Trust', category: 'Architecture', definition: 'A security model that never trusts, always verifies. Every request is authenticated regardless of network location.', related: ['mTLS', 'Security'] }
];
